### ISSUE TITLE
Please create a branch `rails7-shakapacker` based on `rails6-webpacker`

### ISSUE THREAD

**Issue by tagliala** [jamesmartin/inline_svg_test_app#23]
Hi,

I already have a workflow but it misses the branch. If you can create such a branch I will submit a PR

Ref:
- https://github.com/tagliala/inline_svg_test_app/tree/rails7-shakapacker 
- jamesmartin/inline_svg#159
- jamesmartin/inline_svg#158

**Comment by jamesmartin** [comment]
Thanks for the help, @tagliala. New branch [`rails7-shakapacker`](https://github.com/jamesmartin/inline_svg_test_app/tree/rails7-shakapacker) created from `rails6-webpacker`. 

Let's get these tests running and then get your other PRs merged when we're confident.
